server:
  port: 8081
  compression:
    enabled: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai